run-no-observed:
	crossplane render \
  	--include-full-xr \
  	xr.yaml composition.yaml functions.yaml

run-with-observed:
	crossplane render \
  	--observed-resources observed \
  	--include-full-xr \
  	xr.yaml composition.yaml functions.yaml
